persistence:
  enabled: true
  size: 2Gi

initChownData:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
  hosts:
    - grafana.diegofnunesbr.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.diegofnunesbr.com

grafana.ini:
  server:
    root_url: https://grafana.diegofnunesbr.com
  auth.generic_oauth:
    enabled: true
    name: Keycloak
    client_id: grafana
    client_secret: $GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    scopes: openid profile email
    auth_url: https://keycloak.diegofnunesbr.com/realms/home/protocol/openid-connect/auth
    token_url: https://keycloak.diegofnunesbr.com/realms/home/protocol/openid-connect/token
    api_url: https://keycloak.diegofnunesbr.com/realms/home/protocol/openid-connect/userinfo
    jwk_set_url: https://keycloak.diegofnunesbr.com/realms/home/protocol/openid-connect/certs
    use_pkce: true
    use_refresh_token: true
    login_attribute_path: preferred_username
    name_attribute_path: name
    role_attribute_path: "contains(groups[*], 'grafana-admins') && 'Admin' || 'Viewer'"
    role_attribute_strict: false
    allow_sign_up: true
    oauth_auto_login: true

envValueFrom:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      name: grafana-oidc
      key: clientSecret

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir.mimir.svc:8080/prometheus
        isDefault: true
