persistence:
  enabled: true
  size: 2Gi

initChownData:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
  hosts:
    - grafana.diegofnunesbr.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.diegofnunesbr.com

grafana.ini:
  server:
    root_url: https://grafana.diegofnunesbr.com

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir.observability.svc:8080/prometheus
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Mimir
