apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAj74/SDJ/Zmb7KaJCGLeUJPs4q7GyslBQh4T1fr/VmDqAtQ1W+jTE4AtTMxbtucG2rV4TBaoyWmfr4EaGgcQKfAyVhmP6Es2xx93HRcuKdB0ktAWmCec+h70o3Ccvqhxy1QWYpfozbIZHK7rr9l3m8MJO0uTrsWHBb9KsNBPtY4x/qaMOz/mvQCPVteYk2Y/ptonacACmCwVrRxBN4VGeVuywtBBJWwz/8SXud5G7Ex7ipGOynHHz7rUvvw7adnfFWG7ufHanuElyBOMjSTdhQ4M2JOO3AUxwb0DSiVb4XulL1ethUi/wzeHaytmYPpRf457xsgrRMkAo+3doSp7QJZu+cR8mD10xW8/dKlrwVBW9O1QWZF2IwOVMNEu7aagRLZn87LcBq2sPvl4yCDJA8CvXYUn4okKKVHAIByfwjIOWYwvGhckSiZFYGkIZuAxqz9hvnYt1M+vtT73NEdGD1wzHb40LB24viTwKoizS9xmdMt+0oZ7pNjNapamULmtW7Mof/FhBSSHaT1xisC3zS00Ed9uvNL8to4JvLoz2NlFo1L1PqL7y5dDWnF4D5gDsuF0EgBkb4ENg3E3/aM/WGcvq10Hsm1uTAut0MJzngxQTdCsmwzyvb8e9fbeKt7lUA9Il45DPC7mz6mpC0xp9QTvkRT4NxVEDdKHd7fr9LGh+JeySzyfQM6E/nG98blksENuPE70H52Tjk+A==
    admin-user: AgAZtNfzFYJ8gWVrWh8/+FhsCKcQMEMRcPKau1qGYbFLM60Rqdig/CEFL+J6DSH6Hg/WtdJ+4GnbDXo6xovWBlfXBzeiVZJXnYUxw9ESoWHYl4cqdbcsmP0Yxl0n2R2H0PDgKzMOmIIIj8GFn0LMAMMLmgRBo69Gt93BeFVa/1mtW3kUKtFvbXctqjDgNMEMz8OtZZ2iNVYRM+akSXH9zXnep7cYRoBYS/Os/3z0Is/dr9RUswg5OPnwrOSFKknyOTIvDfO0lUIiblPGSXBe8HfVuUi2wQIHoaa+7vRVFOmJhGFMuyCoLi0ZqghkmwXdavTcmbgAeNEtrbL4+J3vRTRglA0d5HwhBugJR5J7gQirKypqP8nyGB/0OQw/5z4E24tNtvjZrU8tIWNK9Zr2fC/otcS0H0SQv+/SaUayVwtw3+XgLVh3CBIC9WaNv6QHkiNsgh+x3iSkLsKLYqCjbu1R9N0+8reuJRnmlM1lHbtoR4S1z2gisBsnZCjwj3Z2oacoXQedWMg51fcr5SPNccobO+mrd2IsQk44vqxnK4//Xv9uARflUfnxWA5hIjdCpNsGbt6Rj+wf4wo3VABmKjuBQR9VX040oQHFCiJCoJt22+DthEOVSawOqeNYUwvskbgBLYJU8Ceceejuhpn9ZUZF2uKMzXgNqxFnmADn2zpRGd+WRCDJeb7mmIe3FFOPLZ+YCGc6hg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: grafana
    type: Opaque

