apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-oidc
  namespace: grafana
spec:
  encryptedData:
    clientSecret: AgBfq9xjVsy0oIW55dOY/p975gPPFsaHbUTNo0XJ8Xl9k3vQIbBgUIylzODDl22UFmBMiQ/qB+R3Kl5aMa4wB0ZP5BRzFhCPdj4emvbKkukkiwoZbDIDu9xqaTJ6s5u9K2kkFOK0Qpj/XXTwiYyo/lU5EdZh5Te2pg8tPfYXPMUJp/owSQoVZgohl2YchZI5DKsadO9lOgsyoodWMIBXPbGR57tudlrr/m8YViRAwYVqv/ufuscFgTmGpOLDNtvfhueQinoDke/WftPbZmZUmyWzdV6NMFPfwzTj+WM5cjiCxYfS7BwBq7R5NmIdqYcO2hTL3Cp4MeXdHt8z83lj6j5QiIvmPSKziCpT/eU82ozhQ3cd1gn8dUxJx2SsCatHTJPGVTbU8G+jLL2m1nq1etFIEWLX1nGZ1CD1GSVo1dNj8SbPWS36sGu/sqdi9Z9L7XRwkwrPRgiAtK4PeldNOMz3sYwW5HGvF8ThQU8t9HxmsMtnDESQhcBUSuYqjc0CmndEz+ln0f2btG8r6pMXQaFuDFOL6ZEtV96YWZD+UUsB1rAAZJ1njRYKDp5ctyExZR2hsI9AguQgmKEnuQsg/tc0t6pXcs+qKtCZqTYYuawK5YabG86p1+plBcxE1+lsr5pMuCNZwhiuqNmjehHE2IL/lF0IN0bbfDMQYTN1GIHdfG6ptC9Bt31OyP3z7sg8RbhFLz1kqqAYSvv85pQelh09wAxfbDzX6OkZ4pNTQ/Xa109N6mMZUTYF43edptl2oNVB5Ee2iiSMOkyy5850ZdemKBoOi4jhXTFAaGRQ0SNlCOjT4Wj6tw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-oidc
      namespace: grafana
    type: Opaque

