apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgABFQJdAjD64s7dd0dFU38bqh502iWJycFrZR4v0Kt/uYIuzfhRJv5YNJv7gOPUv3DE9eA2gTVJ6Yzf9mfxn/Wme3mTdsWjXyEKurpd/kkLr2Iki+d7GWlx++xKFWnYZM1zrRVDNKAGWzEYZi+WkNpT+oi+EygWioyiv2ygn1CzcGrDMQsQVI0Q+22LK9TG8iMgX+pv11SgNxmc7AwmIOSOhfR+So3Dc73K22PiQgYFek93avDO+ZEcALCp3WDmxV6xWIkjZAWT0nF8d6Rvv37T7do9IPc5nehYxSfQn2LPc920gjM9Ni+K0c336BykBob8xMkHGPgWpEahO0bTYZsr95pVgD6jY4BX3R7hUyvoaXPSzH07szzz4zoU0Iwll5AQjcD1/Atyc9lciomndrsUhCDNA2f0g4sXtKPlX5rZxGKIQJcS713rerostdwLhrX7Tj9FA81VAjbShfSaly5ymOb+zx6euILpS1mt7hkAjled7mWAHKoWaQBjFJoVRZiD/ONLrACEear883edMEgBv2y7qV98WHDJjlig2DJuDyJOu+4Uumwg/evlRwYY9vdMEUz5Iy55wiDnVgXMJByam52xatotVMTKk8XzcOspo3rzsK0tVzKVbGxRnvqy23fLzhL9DUHuFJgN8jOtMrFPyKJ3v1SSQhOoGcSXRCRa3jhoDSKCYlFaz0A7beRTwexMGcn/CGahBm1O9Ffs4H+Xii2gz9Y7jRaXtXQCD0jB9A==
    admin-user: AgAzOY8SfJUuoLlbbB0QGLlcDE86FT/pNb4m82XjGGOypk8fGkwsA8f/qiaNd2uYyT4vOmFJ63TYMmSYyaMQFS0QVPtMlFktfnAz8rqH/gYWq0n9LesbM2b5S1HlWYwRCaMF0/vDDdL3opV2Q8yAYq292AxXQRWWW9s50/v4akkhYl99w3CskmaknDekRKN+b7SW8zEWoU0SsYS7nobRyY5tIg8aCwh+O1uUWfQbKnfP2LF9MRwKmcITSS0VpC5hByq1cdhoIuAzkeBByGdqzOwrwgzNYuAjLBY4jhEedYIRX9289AOxkjNy8Pnv4XCrpIUHNtWFGbTtrYL/em5jfXDW4yAzCD24TmSWMeom+LF7sL0plHQmzpUek8eNRrFKPI2K9iBU4sl3sy7PTYmVWOHsxD7NvcjKaICAXrp2OW2T1y+eieQMgpeEAM9i9Y0eRVTMyZQJiQSB2cOeECovMVgsO7ahu8zk7sqahb3pZuOtuJbhhCl1cc2ngJVz2gf6XVOcReNsLGZpcU1MpOb4qqfPXhuCkuMepwGImHGpklxIhzsjigP47vazCAPeRkm52yz9MpyAMcqeHsAouN8XOt1bDcfPU01kYRPnRco1YkKZG3L/nwgW3JmVZ6qb8AvcPfDZV0XVWE2/UrPaZ7uQukVxvScsRSUHba+aW457pgpJ/C4bnCPS7lBuv2/NvTqAWd9SD/HCPA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: grafana
    type: Opaque

